version: 2
jobs:
  build:
    working_directory: ~/firstaid
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: dep-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install pytest
      - save_cache:
          key: dep-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest
